name: flutter_mpesa_stk
description: Flutter Mpesa STK push plugin that allows you to integrate Express Mpesa to your app.
version: 1.0.0+1
homepage: https://github.com/redx1t/flutter_mpesa_stk

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
